-- CreateTable
CREATE TABLE `AnyContent` (
    `CODANY` INTEGER NOT NULL AUTO_INCREMENT,
    `CONTENT` VARCHAR(191) NOT NULL,
    `OWNER` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`CODANY`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
